/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedbackmngt;
//import javax.swing.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sorabh
 */
public class student extends javax.swing.JFrame {
  String rollno;
   PreparedStatement pst1;
   PreparedStatement pst2;
    ResultSet rs;
    
     String path="jdbc:mysql://localhost/";
         String place="feedbackmngt";
         String user="root";
         String psw="";
      
    /**
     * Creates new form student
     */
    public student(String rt) {
        initComponents();
        jLabel2.setText(rt);
           try{
         Connection myconnection;
         
          
     String path="jdbc:mysql://localhost/";
         String place="feedbackmngt";
         String user="root";
         String psw="";String ans="";
      //   String sem=check(rt);
        ////////////////////////////////////////////////
         myconnection=DriverManager.getConnection(path+place, user, psw);
          try{
                           
             String a1="select * from studenttable where Name like ?";
             
             PreparedStatement mystat1=myconnection.prepareStatement(a1);
            // mystat.setString(1,'%'+jTextField1.getText()+'%');
            mystat1.setString(1,rt);
                    
         //    JOptionPane.showMessageDialog(rootPane,"hh");
             ResultSet myresult1=mystat1.executeQuery();
             if(myresult1.next()){
              ans=myresult1.getString("semester");
             }
             else
             {
                   JOptionPane.showMessageDialog(rootPane,"Semester not defined");   
             }
          }
         catch(Exception e){
          //   JOptionPane.showMessageDialog(rootPane,"hk");
             JOptionPane.showMessageDialog(rootPane,"pppppError in query"+e.getMessage());
         }
         finally{
         myconnection.close();
         
     }
               
      /////////////////////////////////////////////////////
         myconnection=DriverManager.getConnection(path+place, user, psw);
          try{
                        
             String a="select * from subject where semester = ?";
             
            // JOptionPane.showMessageDialog(rootPane,"ii");
             PreparedStatement mystat=myconnection.prepareStatement(a);
             
            // JOptionPane.showMessageDialog(rootPane,"ww");
                                   
            
             mystat.setString(1,ans);
             
             
             ResultSet myresult=mystat.executeQuery();
                                  
            
            // DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
             
          //   JOptionPane.showMessageDialog(rootPane,"op");     
               // jComboBox1.addItem("Choose Subject");
            // String id,name,post,phone;
             if(myresult.next()){
                
                do{
             //JOptionPane.showMessageDialog(rootPane,"sy");     
                     jComboBox1.addItem(myresult.getString("name"));
                  
                 }
                 while(myresult.next());
               
         //    JOptionPane.showMessageDialog(rootPane,"pp");  
                 
                 
             }   
             else
             {
              JOptionPane.showMessageDialog(rootPane,"No subject");   
             }
             
        //     JOptionPane.showMessageDialog(rootPane,"hpo");
            // DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
             
            // String id,name,post,phone;
          
         }
                       
         
         catch(Exception e){
             JOptionPane.showMessageDialog(rootPane,"hk");
             JOptionPane.showMessageDialog(rootPane,"pppppError in query"+e.getMessage());
         }
         finally{
         myconnection.close();
         
     }
               
     }   
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(rootPane,"Error in Connection"+e.getMessage());
     }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student  Portal");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Subject" }));
        jComboBox1.setName("Courses"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Teacher" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Course");

        jLabel6.setText("Teacher");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("LogOut");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome");

        jLabel2.setText("jLabel2");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Excellent");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Very Good");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Good");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Poor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, 161, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
                   if(jComboBox1.getSelectedIndex()>0){
//            jTextField6.setText(jComboBox1.getSelectedItem().toString());

            try{
                Connection myconnection;

                myconnection=DriverManager.getConnection(path+place, user, psw);
                try{
                    String a="select * from teachertable where subject=?";
                    PreparedStatement mystat=myconnection.prepareStatement(a);
                    mystat.setString(1,jComboBox1.getSelectedItem().toString());
                    ResultSet myresult=mystat.executeQuery();

                    // DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();

                    // String id,name,post,phone;
                    if(myresult.next()){

                        jComboBox2.removeAllItems();
                        jComboBox2.addItem("Choose Teacher");
                        do{

                            jComboBox2.addItem(myresult.getString("Name"));
                        }
                        while(myresult.next());

                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane,"No Alloted Techer");
                    }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane,"Error in query"+e.getMessage());
                }
                finally{
                    myconnection.close();

                }

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in Connection"+e.getMessage());
            }

        }
        else
        {
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Choose Product");
          //  jTextField6.setText("");
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
           
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(jComboBox2.getSelectedIndex()>0){int a1=0,a2=0,a3=0,a4=0;
//            jTextField6.setText(jComboBox1.getSelectedItem().toString());
            String t=jComboBox2.getSelectedItem().toString();
            try{
                Connection myconnection;

                myconnection=DriverManager.getConnection(path+place, user, psw);
                try{
                    String a="select * from result where name=?";
                    PreparedStatement mystat=myconnection.prepareStatement(a);
                    mystat.setString(1,jComboBox2.getSelectedItem().toString());
                    ResultSet myresult=mystat.executeQuery();

                    // DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();

                    // String id,name,post,phone;
                    if(myresult.next()){
                        
                        a1=Integer.parseInt(myresult.getString("exe"));
                        a2=Integer.parseInt(myresult.getString("vg"));
                        a3=Integer.parseInt(myresult.getString("good"));
                        a4=Integer.parseInt(myresult.getString("poor"));
                        
                                                
                            
                    }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane,"Error in query"+e.getMessage());
                }
                /////////////////
                if(jRadioButton1.isSelected())
                    a1++;
                else if(jRadioButton2.isSelected())
                    a2++;
                else if(jRadioButton3.isSelected())
                    a3++;
                else if(jRadioButton4.isSelected())
                    a4++;
                 try{
                String a="update result set name=?,exe=?,vg=?,good=?,poor=? where name=?";
                // JOptionPane.showMessageDialog(rootPane,"abceewwwwccc");
            
             PreparedStatement mystat1=myconnection.prepareStatement(a);
                mystat1.setString(1,t);
                mystat1.setString(2,Integer.toString(a1));
                mystat1.setString(3,Integer.toString(a2));
                mystat1.setString(4,Integer.toString(a3));
                mystat1.setString(5,Integer.toString(a4));
                mystat1.setString(6,t);
                
                if(mystat1.executeUpdate()==1)
                {
                    JOptionPane.showMessageDialog(rootPane, "Submitted Successfully");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Error in query");
                }
            }

            catch(Exception e){
                JOptionPane.showMessageDialog(rootPane,"Error in query"+e.getMessage());
            }
                    
                    
                
                
                
                
                
                
                
                //////////////////
                finally{
                    myconnection.close();

                }

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in Connection"+e.getMessage());
            }

        }
        else
        {
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Choose Product");
          //  jTextField6.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           int dialogButton = JOptionPane.YES_NO_OPTION;

          int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure you want to LogOut?","Warning!!!",dialogButton);
if(dialogResult == JOptionPane.YES_OPTION){
  
this.dispose();
        login obj=new login();
        obj.setVisible(true);
}
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         String rno="15103011";
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student(rno).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
